### ISSUE TITLE
[Bug] SendXPToOwner removes xp not adds.

### ISSUE THREAD

**Issue by manaphoenix** [SirEdvin/ProgressivePeripherals#24]
### Descripe

Title.

### Steps to reproduce

Try using suckOwnerXP(int limit).

### Version

Own compiled build

### Minecraft, Forge and maybe other related mods versions

Minecraft: 1.16.5 Forge: 36.2.2

**Comment by SirEdvin** [comment]
Oh, this is huge mistake. I will publish 0.0.5 today, it will fix this problem

**Comment by SirEdvin** [comment]
@manaphoenix Fix is ready, you can download fresh mod version from curseforge
