### ISSUE TITLE
[Bug] Reality block crashes game.

### ISSUE THREAD

**Issue by manaphoenix** [SirEdvin/ProgressivePeripherals#27]
### Descripe

If you tell it to turn into the statue block it crashes the game.

### Steps to reproduce

1. place reality block
2. forge into statue block.

### Version

Own compiled build

### Minecraft, Forge and maybe other related mods versions

Minecraft: 1.16.5 Forge: 36.2.2

### Crashlog/log

https://paste.ee/p/JjgGs

**Comment by SirEdvin** [comment]
Hm, I am interested, what result did you expect? 

But, will be fixed, of course, thanks for bug searching, this is truly amazing

**Comment by SirEdvin** [comment]
@manaphoenix  again, thanks for reporting! 

All of reported bugs are fixed in 0.0.6
