### ISSUE TITLE
[Feature] Allow reality block and statue block to be cleared/reset.

### ISSUE THREAD

**Issue by manaphoenix** [SirEdvin/ProgressivePeripherals#30]
### Describe your idea

I think this pretty self explanatory; but, a way to reset the reality and statue block. Otherwise removing them causes all of them to no longer stack for all of eternity.

### Additional context

![image](https://user-images.githubusercontent.com/7843805/128645965-daa14b4b-2a8f-446f-9cf8-3cac7f16a6f5.png)

**Comment by SirEdvin** [comment]
Oh, this sounds like a nice idea, I will do it after finish #18 

I guess, default logic with crafting clears nbt data should be enough

**Comment by SirEdvin** [comment]
With 0.0.9, you able to cleanup any internal data. Just put flexible reality anchor or flexible statue to craft panel
