### ISSUE TITLE
[Bug] Tesselating block model crash

### ISSUE THREAD

**Issue by Wojbie** [SirEdvin/ProgressivePeripherals#33]
### Descripe

User reported this crash happening after joining the server.

### Steps to reproduce

Join the server? I am not able to test it currently. Was only provided with this crash log.

[crash.txt](https://github.com/SirEdvin/ProgressivePeripherals/files/6982077/crash.txt)

Build is: progressiveperipherals-0.0.7.jar

### Version

Own compiled build

### Minecraft, Forge and maybe other related mods versions

Forge 36.1.32, MC 1.16.5

**Comment by SquidDev** [comment]
When you've got more convenient access to the server, might be worthwhile uploading the region file for this chunk. I'd guess there's a turtle tile entity there, which makes no sense.

Geesh, I really hope this isn't a CC:T bug.

**Comment by SirEdvin** [comment]
can it be, that someone tries to forge reality anchor to turtle? 

holy mother of random, I am began to hate this feature)

**Comment by SirEdvin** [comment]
@Wojbie you can try to bypass this problem you can add turtle block IDs to blacklist in config files. This will reset flexible reality anchor that bound to turtle and should fixed the problem (I hope).

I will test my assumption that block with tile entities are creating second tile entity for reality anchor and then ban them from mimicing.

**Comment by SirEdvin** [comment]
Okey, problem is far from my understanding, seems, just mimic turtle is fine

**Comment by Wojbie** [comment]
> 
> 
> When you've got more convenient access to the server, might be worthwhile uploading the region file for this chunk. I'd guess there's a turtle tile entity there, which makes no sense.
> 
> Geesh, I really hope this isn't a CC:T bug.

Sadly i am not gonna be anywhere sane to be able to do that until Monday but i will be easily able then to pull today 5:30 backup and extract that region if its still needed.

**Comment by SirEdvin** [comment]
Okey, this bug is reproducable and @SquidDev according to my testing this bug caused by near block with tile entities, so it is not CC:T related

**Comment by SirEdvin** [comment]
@Wojbie okey, I have upload 0.0.8 to curseforge, that will fix this problem. This is only client-side update
